/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BulkResponse : Success bulk response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkResponse {
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<serde_json::Value>,
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<bool>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl BulkResponse {
    /// Success bulk response
    pub fn new() -> BulkResponse {
        BulkResponse {
            items: None,
            errors: None,
            error: None,
        }
    }
}

