/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FilterNumber : Query filter
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilterNumber {
    #[serde(rename = "filter_field")]
    pub filter_field: String,
    #[serde(rename = "operation")]
    pub operation: String,
    #[serde(rename = "filter_value")]
    pub filter_value: f64,
}

impl FilterNumber {
    /// Query filter
    pub fn new(filter_field: String, operation: String, filter_value: f64) -> FilterNumber {
        FilterNumber {
            filter_field,
            operation,
            filter_value,
        }
    }
}

