/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InFilter : In attribute filter
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InFilter {
    #[serde(rename = "field")]
    pub field: String,
    #[serde(rename = "values")]
    pub values: Vec<serde_json::Value>,
}

impl InFilter {
    /// In attribute filter
    pub fn new(field: String, values: Vec<serde_json::Value>) -> InFilter {
        InFilter {
            field,
            values,
        }
    }
}

