/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PercolateRequest : Object with documents to percolate
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PercolateRequest {
    #[serde(rename = "query")]
    pub query: models::PercolateRequestQuery,
}

impl PercolateRequest {
    /// Object with documents to percolate
    pub fn new(query: models::PercolateRequestQuery) -> PercolateRequest {
        PercolateRequest {
            query,
        }
    }
}

