/*
 * Manticore Search Client
 *
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 3.3.1
 * Contact: info@manticoresearch.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SourceByRules : Query fields to be included/excluded to/from response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SourceByRules {
    #[serde(rename = "includes")]
    pub includes: Vec<String>,
    #[serde(rename = "excludes")]
    pub excludes: Vec<String>,
}

impl SourceByRules {
    /// Query fields to be included/excluded to/from response
    pub fn new(includes: Vec<String>, excludes: Vec<String>) -> SourceByRules {
        SourceByRules {
            includes,
            excludes,
        }
    }
}

